#!/bin/sh
cd "$(dirname "$0")"
rm -rf lib/
rm -rf index.d.ts
mkdir lib
yarn
gulp stylesProduction
tsc ./src/ts/components/ui/VideoSeekSlider.tsx -d --jsx react --target ES5 --outDir ./lib
cp ./lib/VideoSeekSlider.d.ts ./
mv VideoSeekSlider.d.ts index.d.ts